config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'registrations' }
  root 'posts#index'

  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts, only: %i[new create index show destroy] do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :user_id, presence: true
  validates :photo, presence: { message: 'を選択してください' }
  validates :title, presence: true, length: { maximum: 32 }
  validates :caption, length: { maximum: 140 }
  # validates :category_id, presence: { message: 'を選択してください' }

  mount_uploader :photo, PhotoUploader

  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end

  private

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  mount_uploader :profile_photo, PhotoUploader

  # パスワード無しの場合は、paramsからパスワード、パスワード(確認用)を消去
  # これによりパスワード無しでもユーザ名、メールアドレスを編集可能にする
  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name profile_photo profile_photo_cache])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = 'コメントに失敗しました'
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = 'コメントの削除に失敗しました'
    end
  end

  private

  def comment_params
    params.required(:comment).permit(:user_id, :post_id, :comment)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    respond_to :js if @like.save
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    respond_to :js if @like.destroy
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_post, only: %i[show destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
      flash[:success] = '投稿が保存されました'
    else
      render :new
    end
  end

  def index
    @posts = Post.limit(10).includes(:category, :user).order('created_at DESC')
  end

  def show; end

  def destroy
    if @post.user == current_user && @post.destroy
      # リクエスト元情報の取得
      @path = Rails.application.routes.recognize_path(request.referer)
      # リクエスト元がプロフィール画面の場合
      if @path[:controller] == 'users' && @path[:action] == 'show'
        respond_to do |format|
          format.js { flash.now[:error] = '投稿を削除しました' }
        end
      else
        # リクエスト元が画像詳細画面の場合
        redirect_to root_path
        flash[:error] = '投稿を削除しました'
      end
    else
      redirect_to root_path
      flash[:error] = '投稿の削除に失敗しました'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :caption, :photo, :photo_cache, :category_id).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[show]

  def show
    @user = User.includes(posts: [:category]).find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_profile_photo
    'default.png'
  end

  def no_image_photo
    'no_image.png'
  end

  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'success'
    when 'error'
      'danger'
    when 'alert'
      'warning'
    when 'notice'
      'info'
    else
      flash_type.to_s
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_comment').val("");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マッスル博物館</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'favicon.ico' %>
  </head>

  <body>
      <%= render 'partial/navbar'%>
      <%= render 'partial/flash_message'%>
      <%= render 'partial/modal'%>
      <%= yield %>
      <%= render 'partial/footer' %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/partial/_error_message.html.erb
<div id="error_explanation">
  <div class="error_field alert alert-danger" role="alert">
  <% messages = target.errors.full_messages.each do |message| %>
    <div><%= message.html_safe %></div>
  <% end %>
  </div>
</div>

app/views/partial/_flash_message.html.erb
<div id="flash_explanation">
  <% flash.each do |type, message| %>
    <div class='alert alert-<%= bootstrap_class_for(type) %>' role='alert'>
      <%= message.html_safe %></div>
  <% end %>
</div>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © マッスル博物館
      </p>
    </div>
  </div>
</footer>

app/views/partial/_modal.html.erb
<%# ログアウト %>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ログアウトしてよろしいですか？</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">キャンセル</button>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav ml-auto">
        <% unless user_signed_in? %>
          <%= link_to "ログイン", user_session_path, class:"nav-item nav-link" %>
          <%= link_to "新規登録", new_user_registration_path, class:"nav-item nav-link" %>
        <% else %>
          <%= link_to "投稿する", new_post_path, class:"nav-item nav-link" %>
          <%= link_to "プロフィール", user_path(current_user), class:"nav-item nav-link" %>
          <a href="#" data-toggle="modal" data-target="#exampleModal" class="nav-item nav-link">ログアウト</a>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      <strong>and</strong>
  <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
  </strong>

app/views/posts/destroy.js.erb
document.querySelector('#post-<%= @post.id.to_s %>').remove();

<% flash.each do |type, message| %>
  $("#flash_explanation").html("<div class='alert alert-<%= bootstrap_class_for(type) %> ' role='alert'><%= message.html_safe %></div>")
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="jumbotron mt-3">
    <h1 class="display-4">マッスル博物館へようこそ!</h1>
    <hr class="my-4">
    <% unless user_signed_in? %>
      <%= link_to "ログイン", user_session_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="container mt-5 wrap">
  <h1>ランキング</h1>
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-lg-4 col-sm-6">
          <div class="card-wrap">
            <div class="card">
              <div class="card-header align-items-center d-flex">
                <%= link_to user_path(post.user), class: "no-text-decoration" do %>
                  <% if post.user.profile_photo? %>
                    <%= image_tag post.user.profile_photo.url, class: "post-profile-icon border border-light1" %>
                  <% else %>
                    <%= image_pack_tag default_profile_photo, class: "post-profile-icon border border-light1" %>
                  <% end %>
                <% end %>
                <%= link_to user_path(post.user), class: "black-color no-text-decoration",
                  title: post.user.name do %>
                  <strong><%= post.user.name %></strong>
                <% end %>              
              </div>

              <%= link_to(post_path(post)) do %>
                <%= image_tag post.photo.url(:medium), class: "card-img-top" %>
              <% end %>

              <div class="card-body">
                <div class="row parts">
                    <div id="like-icon-post-<%= post.id.to_s %>">
                    <% if user_signed_in? %>
                      <% if post.liked_by(current_user).present? %>
                        <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved  hide-text" %>
                      <% else %>
                        <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                      <% end %>
                  <% end %>
                  </div>
                </div>
                <div>
                  <span><strong><%= post.user.name %></strong></span>
                  <span><%= post.title %></span>
                  <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <%= javascript_pack_tag 'shared/new_url_render' %>
  <%= render 'partial/error_message', { target: @post } %>
<% end %>

<div class="mb-4 mt-5">
  <div class="row">
    <div class="col-lg-3 offset-lg-2 wrap">
        <p>プレビュー</p>
        <% if @post.photo? %>
          <%= image_tag @post.photo.url, id: "preview", class: "img-thumbnail mx-auto d-block" %>
        <% else %>
          <%= image_pack_tag no_image_photo, id: "preview", class: "img-thumbnail mx-auto d-block" %>
        <% end %>
    </div>
    <div class="col-lg-5 wrap">
      <%= form_with model: @post, 
                    local: true do |f| %>

        <div class="form-group">
          <%= f.label :photo %> <span class="badge badge-danger">必須</span>
          <%= f.file_field :photo, onchange: 'previewFileWithId(preview)', class: 'form-control' %>
          <%= f.hidden_field :photo_cache %>
        </div>

        <div class="form-group">
          <%= f.label :title %> <span class="badge badge-danger">必須</span>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :caption %> <span class="badge badge-secondary">任意</span>
          <%= f.text_area :caption, size: "10x5", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :category_id %> <span class="badge badge-danger">必須</span>
          <%= f.collection_select :category_id, Category.all, :id, :category_name, {prompt: "※ 選択してください"}, {class: 'form-control'} %>
        </div>

        <%= f.submit "投稿", class: "btn btn-primary w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photo.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <% if @post.user.profile_photo? %>
                <%= image_tag @post.user.profile_photo.url, class: "post-profile-icon border border-secondary" %>
              <% else %>
                <%= image_pack_tag default_profile_photo, class: "post-profile-icon border border-secondary" %>
              <% end %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>

            <% if user_signed_in? %>
              <% if @post.user_id == current_user.id %>
                <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto delete-post-icon" do %>
                <% end %>
              <% end %>
            <% end %>

          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">
          <% if user_signed_in? %>
              <% if @post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
          </div>

          <div class="like-text" id="like-text-post-<%= @post.id.to_s %>">
            <%= render "like_text", { likes: @post.likes } %>
          </div>

        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
        <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント...(100文字まで)", autocomplete: :off %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap mt-5">
  <div class="row">
    <div class="mx-auto">
      <% if @user.profile_photo? %>
        <%= image_tag @user.profile_photo.url, class: "round-img border border-light1" %>
      <% else %>
        <%= image_pack_tag default_profile_photo, class: "round-img border border-light1" %>
      <% end %>
      <h2 class="text-secondary text-center"><%= @user.name %>
        <% if @user == current_user %>
          <%= link_to "", edit_user_registration_path, type:"button" ,class:"setting" %>
        <% end %>
      </h2>
    </div>
  </div>

  <div class="container wrap">
    <h6 class="text-secondary">投稿画像一覧</h6>
    <div class="row">
      <% @user.posts.each do |post| %>
        <div class="col-sm-6 col-md-4 col-lg-3" id="post-<%= post.id.to_s %>">
          <div class="card-wrap">
            <div class="card">

              <%= link_to(post_path(post)) do %>
                <%= image_tag post.photo.url, class: "card-img-top card-list" %>
              <% end %>

              <div class="card-body">
                <div class="row parts">
                  <% if user_signed_in? %>
                    <div id="like-icon-post-<%= post.id.to_s %>">
                      <% if post.liked_by(current_user).present? %>
                        <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved  hide-text" %>
                      <% else %>
                        <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                      <% end %>
                    </div>
                    <% if post.user_id == current_user.id %>
                      <%= link_to post_path(post), method: :delete, remote: true, class: "ml-auto mx-0 my-auto" do %>
                        <div class="delete-post-icon">
                        </div>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>